services:
  - type: web
    name: santander-news-engine
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      cp news.db $RENDER_PROJECT_DIR/news.db
    startCommand: python server.py
    autoDeploy: true
