services:
  - type: web
    name: santander-news-engine
    env: python
    buildCommand: |
      pip install -r requirements.txt
      cp news.db /opt/render/project/src/news.db
    startCommand: "python server.py"
    plan: free
